### ISSUE TITLE
 Model.save not working

### ISSUE THREAD

**Issue by arijitlaik** [rbeucher/UWGeodynamics#5]
used with the Thermomechanical Model
Traceback (most recent call last):
  File "Tutorial_1_ThermoMechanical_Model.py", line 242, in <module>
    Model.save(filename='twol.json')
  File "/media/student/Outputs/UWgeo/UWGeodynamics/UWGeodynamics/_model.py", line 1516, in save
    json.dump(self, f, sort_keys=True, indent=4, cls=ObjectEncoder)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 443, in _iterencode
    for chunk in _iterencode(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/media/student/Outputs/UWgeo/UWGeodynamics/UWGeodynamics/json_encoder.py", line 8, in default
    return obj.to_json()
  File "/media/student/Outputs/UWgeo/UWGeodynamics/UWGeodynamics/_material.py", line 86, in to_json
    val = self.__dict__[attribute]
KeyError: 'density'

**Comment by arijitlaik** [comment]
fixed
