### ISSUE TITLE
Restarts Still an issue for 1st runs

### ISSUE THREAD

**Issue by arijitlaik** [rbeucher/UWGeodynamics#58]
```
python 1_08_ViscoElasticHalfSpace.ipynb.py
loaded rc file /Users/arijit/codes/UWGeodynamics/UWGeodynamics/uwgeo-data/uwgeodynamicsrc
Maxwell relaxation time =  316.887646408 year 10000000000.0 second
Observation time        =  119999.901227 year 3.786828e+12 second
effective viscosity     =  9.97366222542e+20 pascal * second
        Global element size: 128x32
        Local offset of rank 0: 0x0
        Local range of rank 0: 128x32
[[ 0.    0.05]]
Running with UWGeodynamics version 0.8.0-dev-120d091(HEAD)
Traceback (most recent call last):
  File "1_08_ViscoElasticHalfSpace.ipynb.py", line 244, in <module>
    Model.run_for(600000. * u.years)
  File "/Users/arijit/codes/UWGeodynamics/UWGeodynamics/_model.py", line 1546, in run_for
    self.restart(step=restartStep, restartDir=restartDir)
  File "/Users/arijit/codes/UWGeodynamics/UWGeodynamics/_model.py", line 379, in restart
    step = indices[step]
IndexError: list index out of range
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[41761,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```
due to setting default restartStep=-1

workaround
Model.run_for(1. * u.years,restartStep=None)
Do want to modify all notebooks and examples?

**Comment by rbeucher** [comment]
No I will fix this...

**Comment by arijitlaik** [comment]
Thanks :)

**Comment by rbeucher** [comment]
Sorry for the mess. I am in Barcelona for the Geomod conference. Fixing things in a hurry is usually not a good idea. It has proven right... 😁

**Comment by rbeucher** [comment]
Sorry for the mess. I am in Barcelona for the Geomod conference. Fixing things in a hurry is usually not a good idea. It has proven right... 😁
