### ISSUE TITLE
Error when running model with linkage after some iterations,

### ISSUE THREAD

**Issue by arijitlaik** [rbeucher/UWGeodynamics#9]
Most model run for a few time steps(about .5Ma) then fail with this

In func WeightsCalculator_CalculateAll(): for swarm "E3DSDPHZ__swarm"                                                                                     │··········
        done 33% (10667 cells)...                                                                                                                         │··········
        done 67% (21334 cells)...                                                                                                                         │··········
        done 100% (32000 cells)...                                                                                                                        │··········
WeightsCalculator_CalculateAll(): finished update of weights for swarm "E3DSDPHZ__swarm"                                                                  │··········
Processing surface with Badlands                                                                                                                          │··········
Traceback (most recent call last):                                                                                                                        │··········
  File "two_weak_layers.py", line 122, in <module>                                                                                                        │··········
    Model.run_for(8 * u.megayears, .01 * u.megayears)                                                                                                     │··········
  File "/home/student/ssd/uwgeo/UWGeodynamics/UWGeodynamics/_model.py", line 1321, in run_for                                                             │··········
    self._update()                                                                                                                                        │··········
  File "/home/student/ssd/uwgeo/UWGeodynamics/UWGeodynamics/_model.py", line 1389, in _update                                                             │··········
    self.surfaceProcesses.solve(dt)                                                                                                                       │··········
  File "/home/student/ssd/uwgeo/UWGeodynamics/UWGeodynamics/surfaceProcesses.py", line 51, in solve                                                       │··········
    self._BadlandsModel.solve(dt)                                                                                                                         │··········
  File "/home/student/ssd/uwgeo/UWGeodynamics/UWGeodynamics/linkage/linkage.py", line 140, in solve                                                       │··········
    self.badlands_model.run_to_time(self.time_years+dt_years)                                                                                             │··········
  File "/home/student/pristine/pyBadlands_serial/pyBadlands/model.py", line 315, in run_to_time                                                           │··········
    tflex=flexiso, scum=sload, Te=vTh,Ke=vKe, flexure=fflex, strat=fstrat, ero=fero)                                                                      │··········
  File "/home/student/pristine/pyBadlands_serial/pyBadlands/forcing/forceSim.py", line 752, in apply_XY_dispacements                                      │··········
    raise ValueError('Problem: IDs after merging is on previous vertex position.')

**Comment by arijitlaik** [comment]
this one pops up, if uw resolution is >  badlands resolution, which should not be generally be used.
